# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f35ab4d1369a3711f255295c8402e6d3b07509319633015d270ea82c55a3afd68aeb00a55e7ce17865f629e1737e0bc672862f6c9e9b56d9513d635b72d0782

test:
  secret_key_base: 1267a5a764ae4b9b2508edf88c7658c9c2a2725b00c0ecd5726b86052d0ad9906ec47ba4c9bc0c2027191bf647f2034cd2d1d6f659c546cdbec06674f39492b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
